export const KOTA_KALTIM = [
  "Balikpapan",
  "Bengalon",
  "Berau",
  "Biduk Biduk",
  "Bontang",
  "Kaliorang",
  "Karangan",
  "Kembang Janggut",
  "Kota Bangun",
  "Kutai Lama",
  "Melak",
  "Muara Badak",
  "Muara Kaman",
  "Penajam",
  "Rantau Pulung",
  "Samarinda",
  "Sanga Sanga",
  "Sangatta",
  "Sangkulirang",
  "Sebulu",
  "Sendawar",
  "Separi",
  "Tali Sayan",
  "Tanah Kuning",
  "Tanjung Batu",
  "Tanjung Redeb",
  "Tanjung Selor",
  "Tarakan",
  "Tenggarong",
  "Wahau",
];

export const KOTA_GROUPED = [
  {
    label: "Kota",
    kota: ["Balikpapan", "Bontang", "Samarinda", "Tarakan"],
  },
  {
    label: "Kab. Kutai Kartanegara",
    kota: [
      "Kembang Janggut",
      "Kota Bangun",
      "Kutai Lama",
      "Muara Badak",
      "Muara Kaman",
      "Sanga Sanga",
      "Sebulu",
      "Separi",
      "Tenggarong",
    ],
  },
  {
    label: "Kab. Kutai Timur",
    kota: [
      "Bengalon",
      "Kaliorang",
      "Karangan",
      "Rantau Pulung",
      "Sangatta",
      "Sangkulirang",
      "Wahau",
    ],
  },
  {
    label: "Kab. Kutai Barat",
    kota: ["Melak", "Sendawar"],
  },
  {
    label: "Kab. Berau",
    kota: ["Berau", "Biduk Biduk", "Tali Sayan", "Tanjung Batu", "Tanjung Redeb"],
  },
  {
    label: "Kab. Penajam Paser Utara",
    kota: ["Penajam"],
  },
  {
    label: "Kalimantan Utara",
    kota: ["Tanah Kuning", "Tanjung Selor"],
  },
];
