import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const dataDir = join(dirname(require.resolve("idn-area-data/package.json")), "data");
const outFile = resolve(here, "../../artifacts/api-server/src/lib/kota-indonesia.ts");

function parseCsv(path: string): string[][] {
  const text = readFileSync(path, "utf8").trim();
  const lines = text.split(/\r?\n/);
  lines.shift();
  return lines.map((line) => line.split(","));
}

const provinces = new Map<string, string>();
for (const [code, ...rest] of parseCsv(join(dataDir, "provinces.csv"))) {
  provinces.set(code, rest.join(",").trim());
}

const rows: { nama_kota: string; provinsi: string }[] = [];
for (const [, provinceCode, ...rest] of parseCsv(join(dataDir, "regencies.csv"))) {
  const provinsi = provinces.get(provinceCode);
  const nama_kota = rest.join(",").trim();
  if (!provinsi || !nama_kota) continue;
  rows.push({ nama_kota, provinsi });
}

rows.sort((a, b) =>
  a.provinsi.localeCompare(b.provinsi, "id") || a.nama_kota.localeCompare(b.nama_kota, "id")
);

const body = rows
  .map((r) => `  { nama_kota: ${JSON.stringify(r.nama_kota)}, provinsi: ${JSON.stringify(r.provinsi)} },`)
  .join("\n");

const out = `// AUTO-GENERATED by scripts/src/gen-kota-indonesia.ts — do not edit by hand.
// Source: idn-area-data (Indonesia administrative area data, latest regulation).
// ${provinces.size} provinces, ${rows.length} kabupaten/kota.
export const KOTA_INDONESIA: { nama_kota: string; provinsi: string }[] = [
${body}
];
`;

writeFileSync(outFile, out);
console.log(`Wrote ${rows.length} kabupaten/kota across ${provinces.size} provinces to ${outFile}`);
